print('hahaha')
print('hahaha')
print('aien0320 makes a change')
print('hah')
print('aien0322 was here')
print('I am No.1')
print('hah')
print('aien0322 was here')
print('hah')
print('aien0322 was here')
print('LOL')
print('aien0307 was here')
rint('hah')
print('aien0322 was here')
