print('heheheh')
print('heheheh')
import time
name = input("請輸入姓名:")
print("Hello", name, sep='-', end=',')
time.sleep(0.5)
print("I am your father!!")
time.sleep(3)
print("NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO~~~~~~~~~~~")
time.sleep(2)
print("I'm so sorry", name, ", it's just a joke.")
time.sleep(3)